### ISSUE TITLE
In Windows, cannot drag the window

### ISSUE THREAD

**Issue by rango886** [chrox/readest#1]
## Bug Description

In Windows, cannot drag the window on the main interface
Reading interface, I can drag the window, but there is a high chance that it will not work

**Example:**

In Windows, cannot drag the window on the main interface
Reading interface, I can drag the window, but there is a high chance that it will not work

![image](https://github.com/user-attachments/assets/3b3702c0-fab7-4dc9-b6e0-cafba4316772)

**Comment by chrox** [comment]
Fixed in https://github.com/chrox/readest/commit/96fd2752ff9371ad9dfc104d271adfd81a06b8e8.
