### ISSUE TITLE
Feature Request: config option to disable click navigation

### ISSUE THREAD

**Issue by kratosmy** [chrox/readest#16]
I don't really want to use mouse to control my reading and sometimes a unintentional click will cause the page changes.

**Comment by AdkinsHan** [comment]
i met the same question
there seems a conflict between mouse click and scrolling pages
when i double click a word intend to select the word but it scroll to other paragraph

**Comment by chrox** [comment]
Implemented in #23. You can toggle the 'Disable Click-to-Flip' option in the Misc tab of the Config Dialog to disable click navigation. Closing this now.

![image](https://github.com/user-attachments/assets/a551bd5e-2c47-4bba-8ac4-0b38af0f8112)
