### ISSUE TITLE
🔴 Bug & Suggestion

### ISSUE THREAD

**Issue by Thomas-Harrell** [chrox/readest#18]
---

The web version cannot save settings such as fonts and layout, they will be reset after refreshing the page.

I hope a Docker deployment version can be added in the future.

Since I am still using an older version of macOS, I cannot use Readest.app.

---

**Comment by chrox** [comment]
The config reset issue is fixed.

Note that Readest and the rendering engine is targeting macOS 13.3 and above. See discussions [here](https://github.com/johnfactotum/foliate-js/pull/43). But it should work fine with a recent safari which can be updated on older versions of macOS.

I have little experience on Docker staff especially on macOS. So PR is welcome on the Docker staff.

**Comment by chrox** [comment]
> There's also a small problem in that the Scrolled Mode setting doesn't save after refreshing the page!

I cannot reproduce this neither on Chrome 131.0.6778.140 nor on Safari 17.3.1 (19617.2.4.11.12) on macOS. What's you browser version and you operating system version?
