### ISSUE TITLE
On Windows platform, book thumbnails are not displayed

### ISSUE THREAD

**Issue by rango886** [chrox/readest#2]
## Bug Description

On Windows platform, book thumbnails are not displayed when the program is launched for the second time

### Practical results
![image](https://github.com/user-attachments/assets/d7898f7a-70aa-490d-b0fb-240a9014361e)

### Expected effect
![s7GCROdjXA](https://github.com/user-attachments/assets/dc685ed6-9161-4d96-831c-73bc9b761c6e)

**Comment by chrox** [comment]
I'll look into this issue. Thanks.
