### ISSUE TITLE
Hyphenation for Russian language does not work

### ISSUE THREAD

**Issue by Korb** [chrox/readest#22]
## Bug Description

![2024-12-15_18-14-25](https://github.com/user-attachments/assets/e8e1bc01-4050-4c96-81fe-a257d7540c1b)

## Expected behavior

Regardless of the text alignment method, when hyphenation is enabled, words that are subject to hyphenation must be hyphenated and not carried over to the next line.

## Technical inputs

EPUB2-file
Readest 0.8.3 (2024-12-12)
Microsoft Windows 10.0.19045.5247

**Comment by chrox** [comment]
The hyphenate flag is used here:
https://github.com/chrox/readest/blob/main/apps/readest-app/src/utils/style.ts#L121-L122
If your browser cannot hyphenate on the text, readest cannot hyphenate. Could you debug in the browser console and see if `hyphens` works?

![image](https://github.com/user-attachments/assets/4a2f59ee-5934-4074-a9d6-d3faf6079732)

**Comment by Korb** [comment]
I'm not sure I understand exactly what you want me to do, but here's the same screen as yours with paragraph properties displayed without hyphenation:

![2024-12-15_18-43-46](https://github.com/user-attachments/assets/386ab089-5c41-4d2a-b9b8-192f515007a5)

Readest doesn't use the default browser (Mozilla Firefox 134.0b10 x64 in my case), but Microsoft Edge 109.0.1518.55.

**Comment by chrox** [comment]
Could you also provide the epub file so that I can look into this? Sorry that I don't have any Russian books so that I'm not sure if it has something to do with the hyphenation support of the browser for the language.

**Comment by chrox** [comment]
![image](https://github.com/user-attachments/assets/c0e1ff9c-b870-408f-942d-769d92587f8a)

It seems a problem of Microsoft Edge 109.0.1518.55. The hyphenation of this book works on Chrome and Safari browser and on Safari Webkit.

Can you try updating your Edge WebView2 runtime here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH ?

**Comment by Korb** [comment]
I don't find anything in "Add or Remove Programs" for the query "WebView2". The `MicrosoftEdgeWebView2RuntimeInstallerX64.exe` distribution, downloaded from your link, when launched as administrator, is installed, but in the final stage it spontaneously closes without error messages.

I believe the problem is with my computer and the way Readest works, which is not fully compatible with it at the moment.
