### ISSUE TITLE
Indistinguishable text of the selected tab of the Font & Layout window

### ISSUE THREAD

**Issue by Korb** [chrox/readest#24]
## Bug Description

The text of the selected tab of the Font & Layout window has a color that is indistinguishable from the background used (both use the color `#a6adbb`).

![2024-12-15_18-20-47](https://github.com/user-attachments/assets/0c3e9082-7858-41a8-a1ac-7f093ae615d6)

## Expected behavior

The text of the selected tab of the Font & Layout window has the color `#1d232a`.

## Technical inputs

Readest 0.8.3 (2024-12-12)
Microsoft Windows 10.0.19045.5247

**Comment by chrox** [comment]
It seems also like an issue on lower versions of WebView2. I cannot reproduce this on Edge version 131.0.2903.99 on a Windows 11.

![image](https://github.com/user-attachments/assets/0a693144-2fbc-4b7c-a10b-360fd4cde540)
