### ISSUE TITLE
Ex: In DarkMode, a blank square appears in bottom right corner while scrolling

### ISSUE THREAD

**Issue by smelike** [chrox/readest#28]
## Bug Description

> Application error: a client-side exception has occurred (see the browser console for more information).

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'documentElement')
```

**Comment by chrox** [comment]
1. `Ex` is an example, please change the title to a proper one to describe the issue. If you cannot formalize the title, ask ChatGPT for help.
2. Without steps to reproduce the issue, no one can address this.
