### ISSUE TITLE
There are no window control buttons under Windows platform

### ISSUE THREAD

**Issue by rango886** [chrox/readest#6]
Please add maximize and minimize buttons
![image](https://github.com/user-attachments/assets/5205d34e-fd7a-408c-b442-467eada7c429)

**Comment by chrox** [comment]
To save the header space I intentionally hide the minimize and maximize buttons in the reader page, you have to close the reader page and in the library page there are full window control buttons. Note that Readest keeps in mind with multi-document viewing aka Parallel Read, the header space is precious especially when 2 or more documents are opened.

However, we can show the full window control buttons when there is only one document opened and hide the minimize and maximize buttons when there are more documents opened.

**Comment by chrox** [comment]
Fixed in https://github.com/chrox/readest/commit/a189cd6d4f95f58aa8f47500f729c2436c4996bd. And the code is straightforward, isn't it? 
```diff
diff --git a/apps/readest-app/src/app/reader/components/HeaderBar.tsx b/apps/readest-app/src/app/reader/components/HeaderBar.tsx
index 891dfe8..81fc84b 100644
--- a/apps/readest-app/src/app/reader/components/HeaderBar.tsx
+++ b/apps/readest-app/src/app/reader/components/HeaderBar.tsx
@@ -32,7 +32,7 @@ const HeaderBar: React.FC<HeaderBarProps> = ({
   const headerRef = useRef<HTMLDivElement>(null);
   const { isTrafficLightVisible } = useTrafficLight();
   const [isDropdownOpen, setIsDropdownOpen] = useState(false);
-  const { hoveredBookKey, setHoveredBookKey } = useReaderStore();
+  const { hoveredBookKey, setHoveredBookKey, bookKeys } = useReaderStore();
   const { isSideBarVisible } = useSidebarStore();

   const handleToggleDropdown = (isOpen: boolean) => {
@@ -78,8 +78,8 @@ const HeaderBar: React.FC<HeaderBarProps> = ({
         <WindowButtons
           className='window-buttons flex h-full items-center'
           headerRef={headerRef}
-          showMinimize={false}
-          showMaximize={false}
+          showMinimize={bookKeys.length == 1}
+          showMaximize={bookKeys.length == 1}
           onClose={() => onCloseBook(bookKey)}
         />
       </div>
```
