### ISSUE TITLE
The scroll bar randomly shifts after scrolling, and the page is rearranged due to the scroll bar being hidden after scrolling on the Windows platform

### ISSUE THREAD

**Issue by rango886** [chrox/readest#9]
## Bug Description
https://github.com/chrox/readest/commit/32ffaa0e052c0439d51fba58bd0128fcb7515fb4 The scroll bar randomly shifts after scrolling, and the page is rearranged due to the scroll bar being hidden after scrolling on the Windows platform

![v6L5coND3w](https://github.com/user-attachments/assets/f5b02a36-33cd-4022-9e23-733fc08d64e0)

**Comment by chrox** [comment]
Interesting. We should do the scrollbar auto hide only on macOS in which the scrollbar is overlaying scrollbar. It seems in other platforms the scrollbar will take up some space of the container and when the scrollbar is hidden the layout of the container changed. I’ll fix that shortly.
